build:
  frontend:
    base: client
    output: build
    commands:
      - npm install
      - npm run build
  backend:
    base: app
    output: dist
    commands:
      - npm install
routes:
  - path: /api
    dest: backend
  - path: /
    dest: frontend